name: Build Flutter APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        # هنا نخبر جيت هب بالدخول تلقائياً إلى مجلد مشروعك المرفوع.
        # إذا كان اسم مجلد مشروعك مختلفاً عن "my_awesome_app"، استبدله بالاسم الصحيح المكتوب في جيت هب.
        working-directory: ./my_awesome_app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --android-skip-build-dependency-validation

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: my_awesome_app/build/app/outputs/flutter-apk/app-release.apk
